### PR TITLE
Various fix

### PR DESCRIPTION
**Pull request by khusika**
Looks good to go

### CODE REVIEW

**Comment by khusika** [comment]
Well, i'll make some good PR in your kernel tree. Seems like you will provide another LOS build, am i right? :grin:

**Comment by Flex1911** [comment]
Thanks, I'm going to test this chain

**Comment by Flex1911** [comment]
Pushed.
878120d and 2ceef75 were omitted since both are already fixed by CAF.

**Comment by khusika** [comment]
> Pushed.
> [878120d](https://github.com/Flex1911/android_kernel_xiaomi_msm8953-1/commit/878120d2e02a9884b9b78ca11b50192b59b62fa5) and [2ceef75](https://github.com/Flex1911/android_kernel_xiaomi_msm8953-1/commit/2ceef7553dbf8fd2cd659938d91d2b03c909bf2b) were omitted since both are already fixed by CAF.

Can you point to me about this one https://github.com/Flex1911/android_kernel_xiaomi_msm8953-1/commit/2ceef7553dbf8fd2cd659938d91d2b03c909bf2b ? Last time, i build without this patch and the problem still exist

**Pull request closed without merging**
