### PR TITLE
Minor stuff

### PR DESCRIPTION
**Pull request by khusika**

### CODE REVIEW

**Comment by Flex1911** [comment]
Two camera ones are already picked locally, just didn't push yet. I don't see any point in dts patches tho, neither mido nor tissot are early-mounting the system partition.

**Comment by khusika** [comment]
> Two camera ones are already picked locally, just didn't push yet. I don't see any point in dts patches tho, neither mido nor tissot are early-mounting the system partition.

https://github.com/Flex1911/android_kernel_xiaomi_msm8953-1/commit/461cbc006a03a86ce58f79b0bf54fbc3237d792d
https://github.com/Flex1911/android_kernel_xiaomi_msm8953-1/commit/42e046ad9866475f9c7ec403c4c7abe5d5a28a7c

**Comment by Flex1911** [comment]
https://github.com/Flex1911/android_kernel_xiaomi_msm8953-1/blob/lineage-16.0/arch/arm/boot/dts/qcom/mido/msm8953-general-mido.dtsi#L524
Add fsmgr_flags without verity and system mount here instead.
And for tissot just delete the system part, since we never actually needed it.

**Comment by khusika** [comment]
Done

**Comment by khusika** [comment]
Done

**Comment by Flex1911** [comment]
mido one is g2g, and for tissot it would make more sense to completely remove the system node, as it is unused.

**Comment by Flex1911** [comment]
I fixed your commit myself and pushed.
Thanks!

**Pull request closed without merging**
